// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.0
// source: library.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import { Empty } from "./google/protobuf/empty";

export const protobufPackage = "library";

/** Define the Book message */
export interface Book {
  id: number;
  title: string;
  author: string;
  isbn: string;
  publishedYear: number;
  summary: string;
}

/** Request messages */
export interface CreateBookRequest {
  id: number;
  title: string;
  author: string;
  isbn: string;
  publishedYear: number;
  summary: string;
}

export interface GetBookRequest {
  id: number;
}

export interface UpdateBookRequest {
  id: number;
  title: string;
  author: string;
  isbn: string;
  publishedYear: number;
  summary: string;
}

export interface DeleteBookRequest {
  id: number;
}

/** Pagination and list response */
export interface ListBookRequest {
  page: number;
  pageSize: number;
}

export interface ListBookResponse {
  books: Book[];
  total: number;
}

function createBaseBook(): Book {
  return { id: 0, title: "", author: "", isbn: "", publishedYear: 0, summary: "" };
}

export const Book: MessageFns<Book> = {
  encode(message: Book, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int64(message.id);
    }
    if (message.title !== "") {
      writer.uint32(18).string(message.title);
    }
    if (message.author !== "") {
      writer.uint32(26).string(message.author);
    }
    if (message.isbn !== "") {
      writer.uint32(34).string(message.isbn);
    }
    if (message.publishedYear !== 0) {
      writer.uint32(40).int32(message.publishedYear);
    }
    if (message.summary !== "") {
      writer.uint32(50).string(message.summary);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Book {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBook();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.title = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.author = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.isbn = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.publishedYear = reader.int32();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.summary = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Book {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      title: isSet(object.title) ? globalThis.String(object.title) : "",
      author: isSet(object.author) ? globalThis.String(object.author) : "",
      isbn: isSet(object.isbn) ? globalThis.String(object.isbn) : "",
      publishedYear: isSet(object.publishedYear) ? globalThis.Number(object.publishedYear) : 0,
      summary: isSet(object.summary) ? globalThis.String(object.summary) : "",
    };
  },

  toJSON(message: Book): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.title !== "") {
      obj.title = message.title;
    }
    if (message.author !== "") {
      obj.author = message.author;
    }
    if (message.isbn !== "") {
      obj.isbn = message.isbn;
    }
    if (message.publishedYear !== 0) {
      obj.publishedYear = Math.round(message.publishedYear);
    }
    if (message.summary !== "") {
      obj.summary = message.summary;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Book>, I>>(base?: I): Book {
    return Book.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Book>, I>>(object: I): Book {
    const message = createBaseBook();
    message.id = object.id ?? 0;
    message.title = object.title ?? "";
    message.author = object.author ?? "";
    message.isbn = object.isbn ?? "";
    message.publishedYear = object.publishedYear ?? 0;
    message.summary = object.summary ?? "";
    return message;
  },
};

function createBaseCreateBookRequest(): CreateBookRequest {
  return { id: 0, title: "", author: "", isbn: "", publishedYear: 0, summary: "" };
}

export const CreateBookRequest: MessageFns<CreateBookRequest> = {
  encode(message: CreateBookRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int64(message.id);
    }
    if (message.title !== "") {
      writer.uint32(18).string(message.title);
    }
    if (message.author !== "") {
      writer.uint32(26).string(message.author);
    }
    if (message.isbn !== "") {
      writer.uint32(34).string(message.isbn);
    }
    if (message.publishedYear !== 0) {
      writer.uint32(40).int32(message.publishedYear);
    }
    if (message.summary !== "") {
      writer.uint32(50).string(message.summary);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateBookRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateBookRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.title = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.author = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.isbn = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.publishedYear = reader.int32();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.summary = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateBookRequest {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      title: isSet(object.title) ? globalThis.String(object.title) : "",
      author: isSet(object.author) ? globalThis.String(object.author) : "",
      isbn: isSet(object.isbn) ? globalThis.String(object.isbn) : "",
      publishedYear: isSet(object.publishedYear) ? globalThis.Number(object.publishedYear) : 0,
      summary: isSet(object.summary) ? globalThis.String(object.summary) : "",
    };
  },

  toJSON(message: CreateBookRequest): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.title !== "") {
      obj.title = message.title;
    }
    if (message.author !== "") {
      obj.author = message.author;
    }
    if (message.isbn !== "") {
      obj.isbn = message.isbn;
    }
    if (message.publishedYear !== 0) {
      obj.publishedYear = Math.round(message.publishedYear);
    }
    if (message.summary !== "") {
      obj.summary = message.summary;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateBookRequest>, I>>(base?: I): CreateBookRequest {
    return CreateBookRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateBookRequest>, I>>(object: I): CreateBookRequest {
    const message = createBaseCreateBookRequest();
    message.id = object.id ?? 0;
    message.title = object.title ?? "";
    message.author = object.author ?? "";
    message.isbn = object.isbn ?? "";
    message.publishedYear = object.publishedYear ?? 0;
    message.summary = object.summary ?? "";
    return message;
  },
};

function createBaseGetBookRequest(): GetBookRequest {
  return { id: 0 };
}

export const GetBookRequest: MessageFns<GetBookRequest> = {
  encode(message: GetBookRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int64(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetBookRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetBookRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetBookRequest {
    return { id: isSet(object.id) ? globalThis.Number(object.id) : 0 };
  },

  toJSON(message: GetBookRequest): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetBookRequest>, I>>(base?: I): GetBookRequest {
    return GetBookRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetBookRequest>, I>>(object: I): GetBookRequest {
    const message = createBaseGetBookRequest();
    message.id = object.id ?? 0;
    return message;
  },
};

function createBaseUpdateBookRequest(): UpdateBookRequest {
  return { id: 0, title: "", author: "", isbn: "", publishedYear: 0, summary: "" };
}

export const UpdateBookRequest: MessageFns<UpdateBookRequest> = {
  encode(message: UpdateBookRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int64(message.id);
    }
    if (message.title !== "") {
      writer.uint32(18).string(message.title);
    }
    if (message.author !== "") {
      writer.uint32(26).string(message.author);
    }
    if (message.isbn !== "") {
      writer.uint32(34).string(message.isbn);
    }
    if (message.publishedYear !== 0) {
      writer.uint32(40).int32(message.publishedYear);
    }
    if (message.summary !== "") {
      writer.uint32(50).string(message.summary);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateBookRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateBookRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.title = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.author = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.isbn = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.publishedYear = reader.int32();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.summary = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateBookRequest {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      title: isSet(object.title) ? globalThis.String(object.title) : "",
      author: isSet(object.author) ? globalThis.String(object.author) : "",
      isbn: isSet(object.isbn) ? globalThis.String(object.isbn) : "",
      publishedYear: isSet(object.publishedYear) ? globalThis.Number(object.publishedYear) : 0,
      summary: isSet(object.summary) ? globalThis.String(object.summary) : "",
    };
  },

  toJSON(message: UpdateBookRequest): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.title !== "") {
      obj.title = message.title;
    }
    if (message.author !== "") {
      obj.author = message.author;
    }
    if (message.isbn !== "") {
      obj.isbn = message.isbn;
    }
    if (message.publishedYear !== 0) {
      obj.publishedYear = Math.round(message.publishedYear);
    }
    if (message.summary !== "") {
      obj.summary = message.summary;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateBookRequest>, I>>(base?: I): UpdateBookRequest {
    return UpdateBookRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateBookRequest>, I>>(object: I): UpdateBookRequest {
    const message = createBaseUpdateBookRequest();
    message.id = object.id ?? 0;
    message.title = object.title ?? "";
    message.author = object.author ?? "";
    message.isbn = object.isbn ?? "";
    message.publishedYear = object.publishedYear ?? 0;
    message.summary = object.summary ?? "";
    return message;
  },
};

function createBaseDeleteBookRequest(): DeleteBookRequest {
  return { id: 0 };
}

export const DeleteBookRequest: MessageFns<DeleteBookRequest> = {
  encode(message: DeleteBookRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int64(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteBookRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteBookRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeleteBookRequest {
    return { id: isSet(object.id) ? globalThis.Number(object.id) : 0 };
  },

  toJSON(message: DeleteBookRequest): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DeleteBookRequest>, I>>(base?: I): DeleteBookRequest {
    return DeleteBookRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeleteBookRequest>, I>>(object: I): DeleteBookRequest {
    const message = createBaseDeleteBookRequest();
    message.id = object.id ?? 0;
    return message;
  },
};

function createBaseListBookRequest(): ListBookRequest {
  return { page: 0, pageSize: 0 };
}

export const ListBookRequest: MessageFns<ListBookRequest> = {
  encode(message: ListBookRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.page !== 0) {
      writer.uint32(8).int32(message.page);
    }
    if (message.pageSize !== 0) {
      writer.uint32(16).int32(message.pageSize);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListBookRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListBookRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.page = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.pageSize = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListBookRequest {
    return {
      page: isSet(object.page) ? globalThis.Number(object.page) : 0,
      pageSize: isSet(object.pageSize) ? globalThis.Number(object.pageSize) : 0,
    };
  },

  toJSON(message: ListBookRequest): unknown {
    const obj: any = {};
    if (message.page !== 0) {
      obj.page = Math.round(message.page);
    }
    if (message.pageSize !== 0) {
      obj.pageSize = Math.round(message.pageSize);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListBookRequest>, I>>(base?: I): ListBookRequest {
    return ListBookRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListBookRequest>, I>>(object: I): ListBookRequest {
    const message = createBaseListBookRequest();
    message.page = object.page ?? 0;
    message.pageSize = object.pageSize ?? 0;
    return message;
  },
};

function createBaseListBookResponse(): ListBookResponse {
  return { books: [], total: 0 };
}

export const ListBookResponse: MessageFns<ListBookResponse> = {
  encode(message: ListBookResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.books) {
      Book.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.total !== 0) {
      writer.uint32(16).int32(message.total);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListBookResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListBookResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.books.push(Book.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.total = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListBookResponse {
    return {
      books: globalThis.Array.isArray(object?.books) ? object.books.map((e: any) => Book.fromJSON(e)) : [],
      total: isSet(object.total) ? globalThis.Number(object.total) : 0,
    };
  },

  toJSON(message: ListBookResponse): unknown {
    const obj: any = {};
    if (message.books?.length) {
      obj.books = message.books.map((e) => Book.toJSON(e));
    }
    if (message.total !== 0) {
      obj.total = Math.round(message.total);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListBookResponse>, I>>(base?: I): ListBookResponse {
    return ListBookResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListBookResponse>, I>>(object: I): ListBookResponse {
    const message = createBaseListBookResponse();
    message.books = object.books?.map((e) => Book.fromPartial(e)) || [];
    message.total = object.total ?? 0;
    return message;
  },
};

/** gRPC service definition */
export type LibraryServicesService = typeof LibraryServicesService;
export const LibraryServicesService = {
  createBook: {
    path: "/library.LibraryServices/CreateBook",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: CreateBookRequest): Buffer => Buffer.from(CreateBookRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): CreateBookRequest => CreateBookRequest.decode(value),
    responseSerialize: (value: Book): Buffer => Buffer.from(Book.encode(value).finish()),
    responseDeserialize: (value: Buffer): Book => Book.decode(value),
  },
  getBook: {
    path: "/library.LibraryServices/GetBook",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GetBookRequest): Buffer => Buffer.from(GetBookRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetBookRequest => GetBookRequest.decode(value),
    responseSerialize: (value: Book): Buffer => Buffer.from(Book.encode(value).finish()),
    responseDeserialize: (value: Buffer): Book => Book.decode(value),
  },
  updateBook: {
    path: "/library.LibraryServices/UpdateBook",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: UpdateBookRequest): Buffer => Buffer.from(UpdateBookRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): UpdateBookRequest => UpdateBookRequest.decode(value),
    responseSerialize: (value: Book): Buffer => Buffer.from(Book.encode(value).finish()),
    responseDeserialize: (value: Buffer): Book => Book.decode(value),
  },
  deleteBook: {
    path: "/library.LibraryServices/DeleteBook",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: DeleteBookRequest): Buffer => Buffer.from(DeleteBookRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): DeleteBookRequest => DeleteBookRequest.decode(value),
    responseSerialize: (value: Empty): Buffer => Buffer.from(Empty.encode(value).finish()),
    responseDeserialize: (value: Buffer): Empty => Empty.decode(value),
  },
  listBooks: {
    path: "/library.LibraryServices/ListBooks",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: ListBookRequest): Buffer => Buffer.from(ListBookRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ListBookRequest => ListBookRequest.decode(value),
    responseSerialize: (value: ListBookResponse): Buffer => Buffer.from(ListBookResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): ListBookResponse => ListBookResponse.decode(value),
  },
} as const;

export interface LibraryServicesServer extends UntypedServiceImplementation {
  createBook: handleUnaryCall<CreateBookRequest, Book>;
  getBook: handleUnaryCall<GetBookRequest, Book>;
  updateBook: handleUnaryCall<UpdateBookRequest, Book>;
  deleteBook: handleUnaryCall<DeleteBookRequest, Empty>;
  listBooks: handleUnaryCall<ListBookRequest, ListBookResponse>;
}

export interface LibraryServicesClient extends Client {
  createBook(
    request: CreateBookRequest,
    callback: (error: ServiceError | null, response: Book) => void,
  ): ClientUnaryCall;
  createBook(
    request: CreateBookRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Book) => void,
  ): ClientUnaryCall;
  createBook(
    request: CreateBookRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Book) => void,
  ): ClientUnaryCall;
  getBook(request: GetBookRequest, callback: (error: ServiceError | null, response: Book) => void): ClientUnaryCall;
  getBook(
    request: GetBookRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Book) => void,
  ): ClientUnaryCall;
  getBook(
    request: GetBookRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Book) => void,
  ): ClientUnaryCall;
  updateBook(
    request: UpdateBookRequest,
    callback: (error: ServiceError | null, response: Book) => void,
  ): ClientUnaryCall;
  updateBook(
    request: UpdateBookRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Book) => void,
  ): ClientUnaryCall;
  updateBook(
    request: UpdateBookRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Book) => void,
  ): ClientUnaryCall;
  deleteBook(
    request: DeleteBookRequest,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  deleteBook(
    request: DeleteBookRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  deleteBook(
    request: DeleteBookRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  listBooks(
    request: ListBookRequest,
    callback: (error: ServiceError | null, response: ListBookResponse) => void,
  ): ClientUnaryCall;
  listBooks(
    request: ListBookRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: ListBookResponse) => void,
  ): ClientUnaryCall;
  listBooks(
    request: ListBookRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: ListBookResponse) => void,
  ): ClientUnaryCall;
}

export const LibraryServicesClient = makeGenericClientConstructor(
  LibraryServicesService,
  "library.LibraryServices",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): LibraryServicesClient;
  service: typeof LibraryServicesService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
